#!/bin/sh
# Regenerates Sources/Snicker/EmojiData.swift, the emoji picker's list, from Unicode's emoji-test.txt (the
# full, ordered list with names) and CLDR's English annotations (search keywords like "lol" for 😂).
# Run it when a new Emoji version comes out: `./update-emoji.sh 19.0.0 release-49`.
# Emoji this Mac can't draw yet are hidden at runtime, so a newer list than the OS is safe.
set -e
cd "$(dirname "$0")"

UNICODE_VERSION=${1:-18.0.0}
CLDR_TAG=${2:-release-48-2}
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

curl -sfL "https://unicode.org/Public/$UNICODE_VERSION/emoji/emoji-test.txt" -o "$WORK/emoji-test.txt"
curl -sfL "https://raw.githubusercontent.com/unicode-org/cldr/$CLDR_TAG/common/annotations/en.xml" -o "$WORK/annotations.xml"
curl -sfL "https://raw.githubusercontent.com/unicode-org/cldr/$CLDR_TAG/common/annotationsDerived/en.xml" -o "$WORK/derived.xml"

WORK="$WORK" UNICODE_VERSION="$UNICODE_VERSION" CLDR_TAG="$CLDR_TAG" python3 - <<'PY'
import os, re, xml.etree.ElementTree as ET

work = os.environ["WORK"]
# Apple's picker merges Unicode's first two groups, puts Activity before Travel and leaves out Component
# (bare skin tones and hair styles, which are only building blocks).
CATEGORIES = {
    "Smileys & Emotion": "Smileys & People", "People & Body": "Smileys & People",
    "Animals & Nature": "Animals & Nature", "Food & Drink": "Food & Drink", "Activities": "Activity",
    "Travel & Places": "Travel & Places", "Objects": "Objects", "Symbols": "Symbols", "Flags": "Flags",
}
ORDER = ["Smileys & People", "Animals & Nature", "Food & Drink", "Activity", "Travel & Places", "Objects", "Symbols", "Flags"]
SKIN_TONES = set(chr(c) for c in range(0x1F3FB, 0x1F400))

keywords = {}
for name in ("annotations.xml", "derived.xml"):
    for node in ET.parse(os.path.join(work, name)).iter("annotation"):
        if node.get("type") != "tts" and node.text:
            keywords.setdefault(node.get("cp").replace("️", ""), node.text)

def words(text):
    return [w for w in re.split(r"[\s|:,]+", text.lower()) if w]

categories = {title: [] for title in ORDER}
group = None
for line in open(os.path.join(work, "emoji-test.txt"), encoding="utf-8"):
    if line.startswith("# group: "):
        group = CATEGORIES.get(line[9:].strip())
        continue
    if group is None or "; fully-qualified" not in line:
        continue
    emoji, name = re.match(r".*# (\S+) E\d+\.\d+ (.+)$", line.strip()).groups()
    entries = categories[group]
    # Skin-tone variants follow their base emoji; they're offered from its right-click menu, like Apple's picker.
    if SKIN_TONES & set(emoji) and entries:
        entries[-1]["variants"].append(emoji)
        continue
    own = set(words(name))
    extra = [w for w in dict.fromkeys(words(keywords.get(emoji.replace("️", ""), ""))) if w not in own]
    entries.append({"emoji": emoji, "name": name, "keywords": extra, "variants": []})

lines = []
for title in ORDER:
    lines.append("@" + title)
    for e in categories[title]:
        lines.append("|".join([e["emoji"], e["name"], " ".join(e["keywords"]), " ".join(e["variants"])]))
table = "\n".join(lines)
assert '"""#' not in table and "\\#" not in table

with open("Sources/Snicker/EmojiData.swift", "w", encoding="utf-8") as out:
    out.write(f'''// Generated by update-emoji.sh from Unicode {os.environ["UNICODE_VERSION"]} emoji-test.txt and CLDR {os.environ["CLDR_TAG"]}.
// Do not edit by hand; run ./update-emoji.sh instead.

enum EmojiData {{
    /// "@Category" starts a category; every other line is `emoji|name|keywords|skin-tone variants`.
    static let table = #"""
{table}
"""#
}}
''')
print(f"Wrote {sum(len(v) for v in categories.values())} emoji in {len(ORDER)} categories")
PY
